spring.application.name=SpringAICode

spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.model=gemini-3.6-flash
spring.ai.ollama.chat.model=mistral