spring.application.name=SpringAICode

#spring.ai.openai.api-key=${GEMINI_API_KEY}
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
#spring.ai.openai.chat.model=gemini-3.6-flash
##spring.ai.ollama.chat.model=mistral
#spring.ai.openai.embedding.model=gemini-embedding-001

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001